apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: 'master'
    spec:
      containers:
        - name: redis-master
          image: 'redis:7.0.11-alpine'
          imagePullPolicy: 'IfNotPresent'
          ports:
            - name: http
              containerPort: 6379
              protocol: TCP
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - multinode-m03