apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: http
      protocol: TCP
  selector:
    matchLabels:
      role: master
